### ISSUE TITLE
みんなSpringのコードってどうやって読んでる？

### ISSUE THREAD

**Issue by backpaper0** [tecomi/tecomi-nablarch-spring#2]
## アジェンダ

1. あいさつ(5分)
1. うらがみの読み方を軽く伝える(10分)
       - 資料 https://gist.github.com/backpaper0/759cb12e04ed03a446e75009eec558f2
1. みんながどうやって読んでいるか意見交換(20分)
1. 次回の開催情報など(5分)

(バッファ20分)

**Comment by charon-r13b** [comment]
> みんながどうやって読んでいるか意見交換(20分)

### どういう時に読む？

- 興味
- 開発していて、挙動に疑問を持った時
- 障害解析

### どうやって読む？（方法）

- GitHubで眺める
  - リポジトリを検索する
- Maven依存関係からソースコードを開く
- GitHubリポジトリをcloneしてIDEにインポートして見る

### どうやって読む？（アプローチ）

- トップダウンで把握したい時
  - 主要なクラス（インターフェース）の構成を把握する
    - 責務配置で登場するようなクラス図やシーケンス図を起こすイメージ
  - 知りたいクラスを基点に、実装の詳細 ⇒ クラスやインターフェースの役割に着目 ⇒ のループを繰り返していることが多い
- ピンポイントで見たい時
  - IDEの呼び出し階層を見る
  - デバッガーで止めた時のスタックフレームの階層を見る
  - Thread#dumpStack
- この2つの組み合わせになることも

### 見ておくもの

- リファレンスドキュメント

コードだけを追っていると見落としがちになるので、答え合わせも兼ねる

### Spring Boot／Spring Framework

- Auto Configuration
  - なに（どんなBean）がセットアップされるんだ？を把握する
  - どういう設定のされ方をしているか確認する

**Comment by backpaper0** [comment]
- [Thread#dumpStack()のAPIドキュメント](https://docs.oracle.com/javase/jp/17/docs/api/java.base/java/lang/Thread.html#dumpStack())
- [Springのproxyとfinalメソッド、それからnull](https://backpaper0.github.io/2018/02/22/spring_proxy.html) ... Springの黒魔術の一端を解説した記事。マニアックな内容なので読まなくても問題ないです。

**Comment by backpaper0** [comment]
2023-08-05 17:00-18:00に実施。

**Comment by opengl-8080** [comment]
## 読み方・方法
- 依存に Spring を入れて IDE 機能を使って辿る
- 直接呼び出しているＡＰＩなら、そこから辿る
- 直接呼び出していないところの場合は、デバッガとかで止めて確認
- 場所が分からない場合
    - わざと例外を発生させてスタックトレースから目処をたてる
    - エラーメッセージなどのキーワードで全文検索
- クラス数が多いときはPlantUMLでクラス図を作りながら整理したりもする
    - クラス名がたくさんでてきて、これってどのクラスと関連してたっけ？継承関係あったっけ？ってのが途中で分からなくなってくることがある

## どんなときにコードを読む？
- 拡張したいとき
    - 処理しているところを特定
    - 設定の拡張の余地があるか実装を眺める
        - なんか設定オブジェクトを渡してるぞ？
        - その設定はどこから来てる？
        - とかを辿る
- エラーの原因調査
